# Generated by Django 5.1.3 on 2024-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programmer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='nicknime',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='phone',
        ),
    ]
